apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: quay.io/powercloud/http-echo
        args:
          - "-text=hello-world"

---

kind: Service
apiVersion: v1
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - port: 5678

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-world
spec:
  to:
    kind: Service
    name: hello-world
  tls:
     termination: edge
